CREATE DATABASE db_projeto_estacionamento;

USE  db_projeto_estacionamento;

CREATE TABLE MENSALISTA (
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(20),
    TELEFONE VARCHAR(11)
);

CREATE TABLE CONVENIO (
    CNPJ VARCHAR(20) PRIMARY KEY,
    RAZAOSOCIAL VARCHAR(20),
    TELEFONE VARCHAR(11)
);

CREATE TABLE TARIFA (
    ID INTEGER PRIMARY KEY,
    DIA VARCHAR(10),
    PERIODO VARCHAR(10),
    VALOR DECIMAL(10,2)
);

CREATE TABLE CARRO (
    PLACA VARCHAR(7) PRIMARY KEY,
    MARCA VARCHAR(10),
    MODELO VARCHAR(20),
    COR VARCHAR(10),
    CPF_CLIENTE VARCHAR(11)
);

CREATE TABLE PROCESSAMENTO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(10),
    ENTRADA TIMESTAMP,
    SAIDA TIMESTAMP,
    PLACA_CARRO VARCHAR(7),
    ID_TARIFA INTEGER
);

CREATE TABLE PAGAMENTO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    VALOR DECIMAL(10,2),
    DATAREFERENCIA TIMESTAMP,
    DATAPG TIMESTAMP,
    ID_PROCESSAMENTO INTEGER,
    CNPJ_CONVENIO VARCHAR(20),
    CPF_CLIENTE VARCHAR(11)
);

ALTER TABLE CARRO ADD CONSTRAINT FK_CARRO_1
    FOREIGN KEY (CPF_CLIENTE)
    REFERENCES MENSALISTA (CPF);

ALTER TABLE PROCESSAMENTO ADD CONSTRAINT FK_PROCESSAMENTO_1
    FOREIGN KEY (ID_TARIFA)
    REFERENCES TARIFA (ID);

ALTER TABLE PROCESSAMENTO ADD CONSTRAINT FK_PROCESSAMENTO_2
    FOREIGN KEY (PLACA_CARRO)
    REFERENCES CARRO (PLACA);


ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_1
    FOREIGN KEY (ID_PROCESSAMENTO)
    REFERENCES PROCESSAMENTO (ID);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_2
    FOREIGN KEY (CNPJ_CONVENIO)
    REFERENCES CONVENIO (CNPJ);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_3
    FOREIGN KEY (CPF_CLIENTE)
    REFERENCES MENSALISTA (CPF);