
/* Inserindo novos clientes e seus carros */
INSERT INTO MENSALISTA (CPF, NOME, TELEFONE) VALUES (#VALOR, #VALOR, #VALOR);
INSERT INTO CARRO (PLACA, MARCA, MODELO, COR, CPF_CLIENTE) VALUES (#VALOR, #VALOR, #VALOR, #VALOR);

/* Inserindo novas tarifas ou alterando */
INSERT INTO TARIFA (ID, DIA, PERIODO, VALOR) VALUES (#VALOR, #VALOR, #VALOR, #VALOR);
UPDATE TARIFA SET VALOR = #VALOR WHERE DIA = #VALOR AND PERIODO = #VALOR;

/* Inserindo novas Lojas Conveniadas */
INSERT INTO CONVENIO (CNPJ, RAZAOSOCIAL, TELEFONE) VALUES (#VALOR, #VALOR, #VALOR);

/* Busca Quando a Loja ou Cliente especifico está devendo */
SELECT CNPJ_CONVENIO AS CNPJ, DATAREFERENCIA AS REFERENCIA, VALOR 
FROM PAGAMENTO WHERE DATAPG IS NULL AND CNPJ_CONVENIO = #VALOR ORDER BY DATAREFERENCIA;
SELECT CPF_CLIENTE AS CPF, DATAREFERENCIA AS REFERENCIA
FROM PAGAMENTO WHERE DATAPG IS NULL AND CPF_CLIENTE = #VALOR ORDER BY DATAREFERENCIA;

/* Quitando o pagamento do mensalista e da loja */
UPDATE PAGAMENTO SET DATAPG = CURRENT_TIMESTAMP() WHERE DATAPG IS NULL AND CNPJ_CONVENIO = #VALOR;
UPDATE PAGAMENTO SET DATAPG = CURRENT_TIMESTAMP() WHERE DATAPG IS NULL AND CPF_CLIENTE = #VALOR;

