DELIMITER $$
CREATE PROCEDURE PROC_ENTRADA(IN P_TIPO VARCHAR(10), IN P_PLACA VARCHAR(7), IN P_DIA VARCHAR(10), IN P_MARCA VARCHAR(10), IN P_MODELO VARCHAR(20), IN P_COR VARCHAR(10), OUT RESULT INTEGER, OUT EXC VARCHAR(50))
BEGIN     
	DECLARE P_TARIFA INTEGER;
	DECLARE P_PERIODO VARCHAR(10);
	DECLARE P_HORA TIME;
	DECLARE P_ID INTEGER;
	DECLARE ID_CARRO VARCHAR(7);
        DECLARE excecao SMALLINT DEFAULT 0;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET excecao = 1;
	
START TRANSACTION;

	SET P_HORA = CURRENT_TIMESTAMP();
	IF(P_HORA <= '12:00:00') THEN
		SET P_PERIODO = 'MANHA';
	ELSEIF(P_HORA > '18:00:00') THEN
		SET P_PERIODO = 'NOITE';
	ELSE
		SET P_PERIODO = 'TARDE';
	END IF;	        
	IF(P_TIPO = 'MENSALISTA') THEN
		INSERT INTO PROCESSAMENTO (TIPO, ENTRADA, PLACA_CARRO) VALUES (P_TIPO, P_HORA, P_PLACA);
	ELSE
		SELECT PLACA INTO ID_CARRO FROM CARRO WHERE PLACA = P_PLACA;
		IF(ID_CARRO IS NULL) THEN
			INSERT INTO CARRO (PLACA, MARCA, MODELO, COR) VALUES (P_PLACA, P_MARCA, P_MODELO, P_COR);
		ELSE
			UPDATE CARRO SET MARCA = P_MARCA, MODELO = P_MODELO, COR = P_COR WHERE PLACA = P_PLACA;
		END IF;	
		SELECT ID INTO P_TARIFA FROM TARIFA WHERE DIA = P_DIA AND PERIODO = P_PERIODO;
		INSERT INTO PROCESSAMENTO (TIPO, ENTRADA, PLACA_CARRO, ID_TARIFA) VALUES (P_TIPO, P_HORA, P_PLACA, P_TARIFA);
	END IF;  
	 
	SELECT ID INTO P_ID FROM PROCESSAMENTO WHERE PLACA_CARRO = P_PLACA AND ENTRADA = P_HORA;
	SET RESULT = P_ID;

	IF excecao = 1 THEN
		SET EXC = 'Erro ao gravar dados';
		ROLLBACK;
	ELSE
		SET EXC = 'Salvo com sucesso!';
		COMMIT;
	END IF;

    END$$
DELIMITER ;

CALL PROC_ENTRADA('HORISTA', 'GUI2558', 'UTIL', 'CHEVROLET', 'CAMARO', 'AMARELO', @resposta);
select @resposta;