DELIMITER $$
CREATE PROCEDURE PROC_SAIDA(IN P_ID_PROCESSAMENTO INTEGER, IN P_CNPJ_CONVENIO VARCHAR(20), OUT RESULT VARCHAR(50))
BEGIN
	DECLARE VALORHORA DECIMAL(10,2);
	DECLARE HORAS INT;
	DECLARE TOTALPAGAR DECIMAL(10,2);
	DECLARE P_TIPO VARCHAR(10);
    DECLARE P_SAIDA TIME;
	DECLARE excecao SMALLINT DEFAULT 0;
	DECLARE Verifica_convenio VARCHAR(20); /*verifica se o convenio passado existe*/
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET excecao = 1;

	SET P_SAIDA = CURRENT_TIMESTAMP();
	UPDATE PROCESSAMENTO SET SAIDA = P_SAIDA WHERE ID = P_ID_PROCESSAMENTO;	
START TRANSACTION;
	SELECT TIPO INTO P_TIPO FROM PROCESSAMENTO WHERE ID = P_ID_PROCESSAMENTO;
	IF(P_TIPO = 'HORISTA') THEN
		SELECT VALOR INTO VALORHORA FROM PROCESSAMENTO p INNER JOIN TARIFA t ON p.ID_TARIFA = t.ID WHERE p.ID = P_ID_PROCESSAMENTO;
		SELECT timestampdiff(HOUR, ENTRADA, SAIDA) INTO HORAS FROM PROCESSAMENTO WHERE ID = P_ID_PROCESSAMENTO;
        	SET HORAS = HORAS + 1;
		SELECT (VALORHORA + ((HORAS - 1) * 0.50 * VALORHORA)) INTO TOTALPAGAR;
		IF(P_CNPJ_CONVENIO IS NULL) THEN
			INSERT INTO PAGAMENTO (VALOR, DATAREFERENCIA, DATAPG, ID_PROCESSAMENTO) VALUES (TOTALPAGAR, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), P_ID_PROCESSAMENTO);
        	ELSE
			SELECT CNPJ INTO Verifica_convenio FROM Convenio WHERE CNPJ = P_CNPJ_CONVENIO;
			IF excecao = 1 THEN
				SET RESULT = 'CNPJ não encontrado';
				ROLLBACK;
			ELSE
				SET TOTALPAGAR = TOTALPAGAR * 0.50;
				INSERT INTO PAGAMENTO (VALOR, DATAREFERENCIA, ID_PROCESSAMENTO, CNPJ_CONVENIO) VALUES (TOTALPAGAR, CURRENT_TIMESTAMP(), P_ID_PROCESSAMENTO, P_CNPJ_CONVENIO);
			END IF;
        	END IF;
	END IF;

	IF excecao = 1 THEN
		SET RESULT = 'Erro ao gravar dados';
		ROLLBACK;
	ELSE
		SET RESULT = 'Salvo com sucesso!';
		COMMIT;
	END IF;
END$$
DELIMITER ;

CALL PROC_SAIDA(3, NULL, @X);
SELECT @x;