
DELIMITER $$
CREATE PROCEDURE PROC_CRIAPAGMENSALISTA(IN FIXO DECIMAL(10,2), OUT RESULT VARCHAR(50))
BEGIN
	DECLARE P_REFERENCIA INT;
	DECLARE P_ULTIMADATA TIMESTAMP;
	DECLARE excecao SMALLINT DEFAULT 0;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET excecao = 1;

START TRANSACTION;
	INSERT INTO PAGAMENTO (CPF_CLIENTE) SELECT CPF FROM MENSALISTA;
	SELECT MAX(DATAREFERENCIA) INTO P_ULTIMADATA FROM PAGAMENTO WHERE CPF_CLIENTE IS NOT NULL; 
   	SET P_REFERENCIA = TIMESTAMPDIFF(DAY, P_ULTIMADATA, CURRENT_TIMESTAMP());
	IF (P_REFERENCIA < 30) THEN 
		SET RESULT = 'ERRO AO GRAVAR DADOS!';
		ROLLBACK;
	ELSE
		UPDATE PAGAMENTO SET VALOR = FIXO, DATAREFERENCIA = current_timestamp() WHERE CPF_CLIENTE IS NOT NULL AND DATAREFERENCIA IS NULL;
		SET RESULT = 'SUCESSO!';
	END IF;

	IF(excecao = 1) THEN
		SET RESULT = 'ERRO AO GRAVAR DADOS!';
		ROLLBACK;
	ELSE
		COMMIT;
	END IF;
END$$
DELIMITER ;

CALL PROC_CRIAPAGMENSALISTA(250.00, @X);
SELECT @X;


